### ISSUE TITLE
Grand Theft Auto IV - Lighting artifacts

### ISSUE THREAD

**Issue by pongo1231** [Joshua-Ashton/d9vk#340]
Similar to [here](https://github.com/Joshua-Ashton/d9vk/issues/99) (Intel screenshots), there's a strange line going across the whole screen which seems to be affected by surrounding lights. Though there are no texture related problems like in the screenshots.

![2019-08-27_23-59](https://user-images.githubusercontent.com/4201956/63812437-b12f7e80-c92a-11e9-8b31-15f63095101d.png)

# Software information
Grand Theft Auto IV with the 1.0.7.0 patch applied (previous version), no graphics mods installed, lowest possible settings with 1280x720 resolution, windowed

### System information
- GPU: Intel HD 620
- Driver: Mesa 19.2.0-devel (git-a952333d50)
- Wine version: wine-4.14 (Staging)
- DXVK version: b23a941 (newest commit as of when this was posted)

### Apitrace file(s)
Wasn't sure if wined3d or d9vk was helpful in this case, so here's a trace for each

- wined3d: https://drive.google.com/file/d/1TyOnvRazB8i3iHxZtigaYKIPw7A868TQ/view?usp=sharing

- d9vk: https://drive.google.com/file/d/1SKNu7Y0kQa7PtAzhSr3AAU54sNa-r1qZ/view?usp=sharing

Haven't done a trace on Windows, but if required I can boot up my Windows install for that.

### Log files
- d3d9.log: https://drive.google.com/file/d/1AWXBOBnkyV9Rc8C1VSRDcLPQQG4sjVpi/view?usp=sharing
- d3d11.log: -
- dxgi.log: -

If any more info is needed I'll provide it.

**Comment by money123451** [comment]
wait ... i have seen this issue before in rpcs3 https://youtu.be/mb_Lp7GnuH8?t=22 and it was fixed with https://github.com/RPCS3/rpcs3/pull/5977

**Comment by pongo1231** [comment]
What I also noticed: It'll only appear on surfaces (it won't appear in the sky), also it'll be much more intense during the night than during daytime where it'll only appear partly on surfaces.

Unfortunately the issue still remains with bb9c06c (I know it wasn't addressed directly yet)

**Comment by pongo1231** [comment]
So I just tried it on my Windows partition (with the newest commit) and there are absolutely no issues there. Everything seems to work like it should. So this issue is Linux Intel driver specific.

**Comment by Joshua-Ashton** [comment]
I don't have a solution for r/w hazards on Intel atm

**Comment by pongo1231** [comment]
Thank you for responding!

Unfortunately the issue is still present on my system with 316743f.
