### ISSUE TITLE
The Sims 2 doesn't create a window on Windows 10 with D9VK on my Nvidia GTX 2080

### ISSUE THREAD

**Issue by nelsonjchen** [Joshua-Ashton/d9vk#363]
The Sims 2 is one of those games where it seems compatibility with later versions of Windows and newer hardware such as my Nvidia 2080 is seriously faulty. [I've tried the fixes proposed in some Sims 2 threads about compatibility but the game continues to eventually devolve into purple textures and other serious rendering errors with the stock DX9 implementation after some runtime.](http://bootstrap.modthesims.info/showthread.php?t=610641&c=1&ht=&page=11&pp=25#startcomments) These errors looked *a lot* like the errors that users would get with WineD3D and The Sims 2. Eventually, these errors persist, and somehow brick The Sims 2 installation even after I wipe the save data folders. I think there's some weird incompatibility inside the DX9 support with the modern Nvidia drivers, Windows 10 and however The Sims 2 uses these. I think I've tried all the dances inside that thread I linked and nothing is stable or persistent.

I became aware of DXVK as a usable workaround for Hitman 2 DX11 crashes on Windows with Nvidia before they added native DX12. 🤔 ! Then I found this for DX9. And then @tannisroot posted [an issue on The Sims 2 Wine Patches to run on Linux GitHub Repo](https://github.com/lah7/sims-2-wine-patches/issues/9) showing that this particular DirectX 9 to Vulkan fork had progressed to the point where it was working very well for Linux users and working around the WineD3D issues! 

I extracted the 32-bit DLLs to the game's folder and the game launches, stays running inside Task Manager, but no window appears. In the D9VK logs, I appear to be getting `VK_ERROR_DEVICE_LOST` errors.

https://gist.github.com/nelsonjchen/34c34dae85aae45e41018b584e6a8993#file-sims2ep9_d3d9-log-L118-L127

I provide a trace file below with the native DX9. I launched the game, a window appeared, I exited the game after the loading was completed. 

For reference, I've been using these shortcut arguments: `"C:\Program Files (x86)\Origin Games\The Sims 2 Ultimate Collection\Fun with Pets\SP9\TSBin\Sims2EP9.exe" -w -CPUCount:1`

I've also tried telling the game to limit its texture memory to 1024MB. 

![image](https://user-images.githubusercontent.com/5363/64485955-bec2ef00-d1db-11e9-8493-c7334b9c0b25.png)

Please let me know if I've missed anything, if more info/tracing is needed, or any other way I can help. I'm really eager to see if this will help the community's compatibility issues.

### Software information
The Sims 2 Ultimate Collection on Origin
4GB Patch applied

### System information
- GPU: Nvidia 2080
- Driver: 436.15.0
- Wine version: Windows 10 1903
- DXVK version: master.c434254b5f8211d913d102af9c756c87115a9d3c

### Apitrace file(s)
- https://drive.google.com/file/d/1ofNnypTg7CGlecMxKzo6X5_ZutsVTZRY/view?usp=sharing

### Log files
- d3d9.log: https://gist.github.com/nelsonjchen/34c34dae85aae45e41018b584e6a8993
- d3d11.log: Not Found
- dxgi.log: Not found

**Comment by mozo78** [comment]
The answer is simple - don't use Microsoft's garbage heap but Linux - win-win situation ;)

**Comment by nelsonjchen** [comment]
@mozo78 I seriously did consider doing that for myself. But I wouldn't have a reasonable answer for others and the best way to keep a game alive is to always have more people playing and enjoying it. [We can't have game preservation just be some YouTube videos.](https://www.youtube.com/watch?v=QRyhdZncQsw)

Seeing #306 made me decide to go ahead to collect data and post this issue.

**Comment by mozo78** [comment]
More people can play it on Linux too. Nobody really needs Windows. It's just a nasty old habit.

**Comment by Joshua-Ashton** [comment]
Can you try the latest master builds?
https://git.froggi.es/joshua/d9vk/-/jobs
I fixed a NV-only regression recently which could cause device loss from a wonky shader.

**Comment by nelsonjchen** [comment]
@Joshua-Ashton 

https://gist.github.com/nelsonjchen/0fb8c410bc614af3358c8cf7f994e4bb

master@717d9c48

`VK_ERROR_DEVICE_LOST` , no window , and running in Task Manager still.

**Comment by nelsonjchen** [comment]
A commit has landed on master which now allows The Sims 2 to run by limiting max available memory: https://github.com/Joshua-Ashton/d9vk/commit/a5b0424e4bf33099152d93c1cfcfed61769d29a4

**Comment by nelsonjchen** [comment]
Please keep this issue open for a while. I want to test with 1.5GB of Max Available memory which I admittedly pulled out of my ass. The new default of 3.5GB still crashes when entering some lots but the 1.5GB asspull seems to be very stable. Or should I make a new issue?

**Comment by Joshua-Ashton** [comment]
Yes
