### ISSUE TITLE
Dead Space lighting issue

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#37]
Dead Space now renders in-game with Low settings, however, there are issues with lighting and misaligned menus. I'll try making a video later once I figure out why OBS won't record full screen games.

### Software information
Dead Space Low settings preset

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: Staging 3.21
- D9VK version: c37ae6d7fc23369e24b5a4a997806fa0c3efcc88

### Apitrace file(s)
- https://drive.google.com/open?id=1oG9LyEzwsar2Nm1Ol5KdhwrOyTgzQuBj

### Log files
[Dead Space_d3d9_log.zip (568MB decompressed)](https://github.com/Joshua-Ashton/d9vk/files/3100716/Dead.Space_d3d9_log.zip)

**Comment by DaRkL3AD3R** [comment]
Dead Space is now looking almost perfect but shadow maps are broken and appear as just shadow acne across all surfaces where a dynamic light source is. Oddly enough, Dead Space 2 works flawlessly even with the shadow maps.

Both games suffer from double mouse cursor issues where there is always a floating cursor visible at all times.

**Comment by DaRkL3AD3R** [comment]
As of release 0.12 double mouse cursor glitch is fixed. Shadow maps in DS1 remain broken.

**Comment by AccountOneOff** [comment]
This seems good now.

**Comment by DaRkL3AD3R** [comment]
Did you test on a custom built nightly and confirm it's fixed? Because on release 0.12 I can confirm the shadows are still broken.

**Comment by AccountOneOff** [comment]
Master

**Comment by NerosTie** [comment]
On my side, the shadows are still broken with the last master.
