### ISSUE TITLE
Rocket League crashing with 0.10

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#93]
I've crashed three times now during competitive unfortunately I had logging disabled. Opening this in case it happens again.

### Software information
Settings: ![Screenshot from 2019-05-07 02-18-38](https://user-images.githubusercontent.com/15083452/57338797-8e5f2d00-70e3-11e9-9ef3-abbbf9915891.png)

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: Staging 4.6
- D9VK version: 0.10

### Apitrace file(s)
- https://drive.google.com/open?id=10dGL1Z-tsyyszW1XmrMMboduGy9ZChBp

**Comment by tannisroot** [comment]
Can you try with latest master?

**Comment by AccountOneOff** [comment]
[RocketLeague_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3168752/RocketLeague_d3d9.log)

Makes sense it's a 32bit game after all.

**Comment by tannisroot** [comment]
So it still crashes with master? It's just there were some fixes that were meant to address allocation issues.
If the issue persists, try setting `WINE_LARGE_ADDRESS_AWARE` envar to `1`.

**Comment by Joshua-Ashton** [comment]
This should be fixed by 6573579ef2e92bdbec8cd64fcf14d0ab825de4dd, can you retest?

**Comment by AccountOneOff** [comment]
@tannisroot yup, used that with that follow up. @Joshua-Ashton will retest later when I have time.

**Comment by AccountOneOff** [comment]
This time it crashed in Training while it was loading up a match.

[RocketLeague_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3169612/RocketLeague_d3d9.log)

```
Warning, Unknown language extension . Defaulting to INT
ScriptWarning, URL is empty


	WebCache_X Transient.WebCache_X_0


	Function ProjectX.WebCache_X:SyncDataInternal:0020


Script call stack:
	Function TAGame.CDNObject_TA:Construct
	Function TAGame.CDNObject_TA:HandleUrlChanged
	Function TAGame.CDNObject_TA:Init
	Function ProjectX.CacheTimer_X:SetEnabled
	Function ProjectX.CacheTimer_X:OnEnabled
	Function ProjectX.CacheTimer_X:OnExpired
	Function TAGame.CDNObject_TA:HandleCacheExpired
	Function ProjectX.OnlineResource_X:SyncData
	Function ProjectX.OnlineResource_X:RetrySync
	Function ProjectX.WebCache_X:SyncData
	Function ProjectX.WebCache_X:SyncDataInternal

RPC Error (failure): Service=Clubs/GetPlayerClubDetails, Type=ClubNotFound, Code=-1, Message=
\src\common\html\chrome_ipc_client.cpp (763) : Assertion Failed: Failed to connect to master html process, created shared memory (spawn time 60.12)
PsyNetStaticData could not find class 'PsyNetUrl_X'
FJsonStructReader - cannot find property URL because Struct has not been set.
Warning, Failed to load 'SwfMovie GFx_LoadingScreen.LoadingScreen': Failed to find object 'SwfMovie GFx_LoadingScreen.LoadingScreen'
AL lib: (EE) ReleaseThreadCtx: Context 0x7c4728c0 current for thread being destroyed, possible leak!
Timed out waiting for game mapping!
Setting breakpad minidump AppID = 252950
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198259545524 [API loaded no]
```

**Comment by Joshua-Ashton** [comment]
That's not my error.

**Comment by Bettehem** [comment]
I have Rocket League crashing after installing d9vk too. The game won't start again before I restart steam completely. The crashes seem to happen at random intervals, so I don't quite know what specific event in game would cause this.

**Comment by kelvinhbo** [comment]
I have the same problem with Rocket League,it just crashes randomly. None of this options work PROTON_FORCE_LARGE_ADDRESS_AWARE
WINE_LARGE_ADDRESS_AWARE
Too bad because the performance is way better using D9VK than with the native port , I hope this gets resolve soon.

**Comment by Joshua-Ashton** [comment]
Logs and any crash reports would be helpful

**Comment by kelvinhbo** [comment]
Sorry about that, here is the log.

[steam-252950.log](https://github.com/Joshua-Ashton/d9vk/files/3244906/steam-252950.log)

**Comment by K0bin** [comment]
```err:   DxvkMemoryAllocator: Memory allocation failed
  Size:      223608832
  Alignment: 256
  Mem flags: 0x7
  Mem types: 0x681```

If the game is 32bit, please try setting the Large Address Aware flag.

**Comment by kelvinhbo** [comment]
I have tried this two options both on the set launch options of Steam and on the user_settings.py in the Proton folder, but the game still crashes randomly.

Steam launch option:
PROTON_FORCE_LARGE_ADDRESS_AWARE=1
WINE_LARGE_ADDRESS_AWARE=1

user_settings.py 
"PROTON_FORCE_LARGE_ADDRESS_AWARE":"1",
     "WINE_LARGE_ADDRESS_AWARE":"1",

**Comment by z0n** [comment]
Hi, I'm also experiencing crashes in Rocket League using D9VK 0.12. I've installed it using Steam Play and am running it using Lutris (Lutris runtime is disabled in the options though). 

### System information
- OS: Arch Linux
- GPU: GTX 1080 Ti
- Driver: 430.26
- Wine version: Proton 4.2 installed via Steam
- D9VK version: 0.12

I've taken inspiration from [this](https://lutris.net/games/install/10989/view) Lutris install script, I didn't install BakkesMod though.

My environment variables as configured in Lutris:
- PROTON_FORCE_LARGE_ADDRESS_AWARE: 1
- WINE_LARGE_ADDRESS_AWARE: 1
- VK_INSTANCE_LAYERS: VK_LAYER_LUNARG_standard_validation
- DXVK_LOG_LEVEL: debug
- __GL_THREADED_OPTIMIZATIONS: 1
- mesa_glthread: 'true'

Here are some logs, hope they help:
- [RocketLeague_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3384133/RocketLeague_d3d9.log)
- [RocketLeague_Lutris.log](https://github.com/Joshua-Ashton/d9vk/files/3384134/RocketLeague_Lutris.log)

This crash happened in the middle of a 3vs3 competitive game. I've also experienced crashes and freezes when launching the game (before the first logo) or in the main menu.

Feel free to ask if you need more information.

**Comment by Bettehem** [comment]
I have noticed that the crashes occur most often when going to the main menu after playing a match

**Comment by z0n** [comment]
Decided to try 0.20 and unfortunately, it still crashes occasionally.

**Comment by kelvinhbo** [comment]
I have been without crashes in this game for about 3 days now, not an ideal solution but completely disabling swap memory seems to be doing the trick for me.
Disabled the swap point in /etc/fstab, and set /proc/sys/vm/swappiness to 0
I also installed this custom version of Proton https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/4.14-GE-2

**Comment by kelvinhbo** [comment]
Never mind, it still crashes, same memory problem.

**Comment by raiscan** [comment]
I have the same issue; crashes when joining a new match, usually, or when party members switch their car a lot in the main menu.

[steam-252950.log](https://github.com/Joshua-Ashton/d9vk/files/3648475/steam-252950.log)

This log is from me launching the game and heavily navigating around the garage-related menus. It triggered it after a few minutes, but it happens much quicker when you are in an online party, too.

I'm happy to help with any testing as d9vk makes Rocket League perform phenomenally on Linux!

**Comment by kelvinhbo** [comment]
I can confirm the problem have been fixed with Proton 4.11.6 on Steam, have tested on 2 different systems and they have been working perfectly no crashes.

**Comment by Joshua-Ashton** [comment]
Please test with https://git.froggi.es/joshua/d9vk/-/jobs/954

**Comment by horstderheld** [comment]
still crashing
[steam-252950.log](https://github.com/Joshua-Ashton/d9vk/files/3785754/steam-252950.log)

**Comment by Joshua-Ashton** [comment]
Hi I'm completely unable to replicate this crash... I've played a few matches (albeit with bots as I don't have any friends with this game)

Is anyone here playing on AMD and experiencing this?

If you're playing on NV, please ensure you have the latest D9VK and the latest NV drivers (and whatever fix was needed for dxvk 1100 for dkms stuff)

**Comment by horstderheld** [comment]
would an apitrace help you to track it down?

**Comment by Joshua-Ashton** [comment]
No, I own the game.

**Comment by Nonecaster** [comment]
I'm playing on AMD and experiencing crashes using D9VK (Proton 4.11-8).  The crashes mostly happen before/after online matches, and more frequently if I choose "leave match" right after a match has ended.

**Comment by Joshua-Ashton** [comment]
Can you test on master?

**Comment by Nonecaster** [comment]
I tried it briefly (hopefully did it right), and it didn't crash. However, the game hung on every menu screen for a long time, and the initial load was very long too. I only had time to play two matches but the gameplay seemed fine. I took a few screenshots if you want to see the DXVK HUD and game stats which you can find here: https://www.dropbox.com/sh/6yz5vqlmgeq4ndn/AADUMoAOFbv8Hbfu40nT4PbIa?dl=0

Sorry for the large images. I'm playing at 4K and only realized to change the resolution for the last one!

**Comment by kelvinhbo** [comment]
With Proton 4.11-8 the game runs but extremely laggy to the point where is unplayable, with D9VK version .30 the game crashes constantly when playing online, I had to downgrade to Proton 4.11-7, with this version the game is stable and works great.

**Comment by Joshua-Ashton** [comment]
This isn't my bug.

**Comment by VGHS-lucaruby** [comment]
I have tested with the latest master using Proton-TKG to circumvent proton 4.11.8's loading issues.
The game is still crashing after a few games sadly :(
Here are my D3D9 log and DXGI logs hope these help in some way but they are the same as my others from earlier versions :(
[RocketLeague_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3882579/RocketLeague_d3d9.log)
[RocketLeague_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3882580/RocketLeague_dxgi.log)

**Comment by Joshua-Ashton** [comment]
I can't fix it without a solid repro case and I've played 5 matches and got no crashes here.

**Comment by VGHS-lucaruby** [comment]
I'm more than happy to help you, either test or work out differences that make other peoples crash repeatably and yours not.

**Comment by Joshua-Ashton** [comment]
Well the bug only seems to be happening on people with NV atm, I am curious as to if anyone can repro it on AMD.

**Comment by VGHS-lucaruby** [comment]
Nonecaster, says he's on AMD with the same issues. Though he could not test master due to 4.11.8 issues.

**Comment by kelvinhbo** [comment]
Keep in mind that the crashes don't happen for me on my Fedora GTX1060 laptop and my Arch Desktop with a GTX 1080 ti while using Proton 4.11-7.

**Comment by VGHS-lucaruby** [comment]
Strange though as people seem to have been having the issue on 4.11-7 aswell.

I have just been looking around Reddit to see if this issue has ever been present on windows, which its seems to have been. I'm starting to think that this is an issue with the game which windows does a better job of handling vs DXVK but I really hope not, as the chances of Pysonix fixing an issue like that.

I've been doing testing most of the day trying to find the cause but I'm no closer :( so back to trying to find a cause lol

**Comment by kelvinhbo** [comment]
The game is not the problem I have been playing it since it came out on Windows on a multitude of cards, never had the crash there, the native Linux port is bad, you get a fraction of the frame rate and the controls have a huge delay, for me with D9VK the game actually runs better than on Windows.

Try this:
Delete this folder: ~/.local/share/Steam/steamapps/compatdata/252950/
Then install Proton 4.11-7 on: ~/.local/share/Steam/compatibilitytools.d/

**Comment by VGHS-lucaruby** [comment]
I'm in the process of trying a fresh install with the latest master release and have only had 2 crashes on the initial startup after the reinstall so far but will have to wait and see if there are any in-game. If I do crash time to try 4.11-7, and yes I find it super unlikely to be the game but I thought I throw out the fact that this issue has also been seen on windows with this title .

**Comment by VGHS-lucaruby** [comment]
Well just played for over an hour now on a fresh prefix and install of RL with the latest master DXVK and Proton-TKG. This is much longer than I had been able to in the past so I believe my prior statement that master doesn't work is wrong and it does, it was likely that my prefix was messed up from previous version/crashes.

**Comment by VGHS-lucaruby** [comment]
played about 3 hours on the latest build you referenced this issue with and I have had no crashes since then. So for me at least the issue is resolved.

**Comment by cain05** [comment]
I tried the game the other day, and after a match it froze and I got a pop up saying it ran out of video memory, similar to what's happening in Borderlands 2 when I have textures set above medium.   https://github.com/Joshua-Ashton/d9vk/issues/170  I was using the newest proton, 4.11-11 I think it is.

**Comment by VGHS-lucaruby** [comment]
This issue has for me at least gotten better to the point where to only crashes in menus but the issue is still very much present after a few games. As I said before I am happy to offer up my system to help you test as you have stated you can not reproduce the issue.

**Comment by z0n** [comment]
It's still crashing to desktop for me during matches (happened once in 2vs2 competitive today). 
Other than that, it crashed a few times after casual 2vs2 and 3vs3 matches. I still have to play a few matches for it to crash but it's still not fully working unfortunately.
My current setup:
* OS: Arch Linux
* Kernel: 5.4.5-1-ck-skylake
* GPU: GTX 1080 Ti
* NVIDIA driver: 440.44
* Proton version: 4.11-11 with PROTON_USE_D9VK=1

I didn't catch any logs unfortunately.
